/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FacultyController;
import Controller.SubjectController;
import DTO.FacultyDTO;
import DTO.SubjectDTO;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.security.jca.GetInstance;
import utilities.CustomizeTable;
import utilities.CustomizeTableHeader;

/**
 *
 * @author dimut
 */
public class Instructor1 extends javax.swing.JFrame {
    private int facultyLoadCount;
    private static Instructor1 instructor;
    private int subjectLoadCount;

    /**
     * Creates new form Instructor
     */
    private Instructor1() {
        initComponents();
        setSize(2270, 1140);
        loadFaculties();
    }
    public static Instructor1 getInstance(){
        if(instructor==null){
            instructor=new Instructor1();
        }
        return instructor;
    }
     public void setInitialStage() {
        loadFaculties();
        loadSubjectCodes();
        setSubjectName();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cmbgender = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txttelephone = new javax.swing.JTextField();
        txtinsid = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinstructor = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        cmbFaculty = new javax.swing.JComboBox();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cmbsubjects = new javax.swing.JComboBox();
        txtemail = new javax.swing.JTextField();
        lblsubject = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jPanel1.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel17.setText("INSTRUCTOR ID");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(60, 140, 209, 41);

        cmbgender.setBackground(new java.awt.Color(240, 240, 240));
        cmbgender.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        cmbgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MALE", "FEMALE", " " }));
        cmbgender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbgenderItemStateChanged(evt);
            }
        });
        cmbgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgenderActionPerformed(evt);
            }
        });
        jPanel1.add(cmbgender);
        cmbgender.setBounds(1070, 330, 110, 40);

        jLabel18.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel18.setText("TELEPHONE");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(810, 150, 209, 41);

        jLabel19.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel19.setText("FACULTY");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(60, 50, 209, 41);

        jLabel20.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel20.setText("GENDER");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(810, 330, 209, 41);

        jLabel21.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel21.setText("FIRST NAME");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(60, 240, 209, 41);

        jLabel22.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel22.setText("LAST NAME");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(60, 340, 209, 41);

        jLabel23.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel23.setText("SUBJECT NAME");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(1570, 150, 209, 41);

        txtfname.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfname);
        txtfname.setBounds(300, 240, 430, 40);

        txttelephone.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        txttelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelephoneActionPerformed(evt);
            }
        });
        jPanel1.add(txttelephone);
        txttelephone.setBounds(1070, 150, 430, 40);

        txtinsid.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        txtinsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinsidActionPerformed(evt);
            }
        });
        jPanel1.add(txtinsid);
        txtinsid.setBounds(300, 140, 430, 40);

        txtlname.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtlname);
        txtlname.setBounds(300, 340, 430, 40);

        txtaddress.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtaddress);
        txtaddress.setBounds(1070, 60, 430, 40);

        tblinstructor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Instructor ID", "Name", "Faculty", "Address", "Telephonel", "Gender", "Subject"
            }
        ));
        jScrollPane1.setViewportView(tblinstructor);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 630, 2010, 480);

        jLabel24.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel24.setText("EMAIL");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(810, 250, 209, 41);

        cmbFaculty.setBackground(new java.awt.Color(240, 240, 240));
        cmbFaculty.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        cmbFaculty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFacultyItemStateChanged(evt);
            }
        });
        cmbFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFacultyActionPerformed(evt);
            }
        });
        jPanel1.add(cmbFaculty);
        cmbFaculty.setBounds(300, 50, 430, 40);

        btnupdate.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(1470, 550, 200, 50);

        btndelete.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete);
        btndelete.setBounds(1720, 550, 200, 50);

        btnsave.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave);
        btnsave.setBounds(1210, 550, 200, 50);

        jLabel25.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel25.setText("ADDRESS");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(810, 60, 209, 41);

        jLabel26.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel26.setText("SUBJECT CODE");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(1570, 60, 209, 41);

        cmbsubjects.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jPanel1.add(cmbsubjects);
        cmbsubjects.setBounds(1830, 60, 300, 40);

        txtemail.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail);
        txtemail.setBounds(1070, 250, 430, 40);

        lblsubject.setFont(new java.awt.Font("Bookman Old Style", 0, 20)); // NOI18N
        jPanel1.add(lblsubject);
        lblsubject.setBounds(1830, 150, 410, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(3, -10, 3190, 1150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void cmbFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFacultyActionPerformed

    private void cmbFacultyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFacultyItemStateChanged
        if(facultyLoadCount>0){
            loadSubjectCodes();
        }
    }//GEN-LAST:event_cmbFacultyItemStateChanged

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtinsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinsidActionPerformed

    private void txttelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelephoneActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void cmbgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbgenderActionPerformed

    private void cmbgenderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbgenderItemStateChanged
        // if (facultyLoadCount > 0) {
            // loadTable();
            //}
    }//GEN-LAST:event_cmbgenderItemStateChanged

    /**
     * @param args the command line arguments
     */
   /* private void customizeLecturerSubjectsTable() {
        tblinstructor.setDefaultRenderer(Object.class, new CustomizeTable());
        tblinstructor.getTableHeader().setDefaultRenderer(new CustomizeTableHeader());
        tblinstructor.setRowHeight(30);
        tblinstructor.setShowGrid(true);
        tblinstructor.setFont(new Font("", 0, 18));
        pneinstructor.getViewport().setBackground(Color.WHITE);

        //tblSubjects.setDefaultRenderer(Object.class, new CustomizeTable());
        //tblSubjects.getTableHeader().setDefaultRenderer(new CustomizeTableHeader());
        //tblSubjects.setRowHeight(30);
        //tblSubjects.setShowGrid(true);
        //tblSubjects.setFont(new Font("", 0, 18));
        //pneSubjects.getViewport().setBackground(Color.WHITE);
    }*/
    private void loadFaculties(){
        try {
            facultyLoadCount=0;
            cmbFaculty.removeAllItems();
            ArrayList<FacultyDTO> facultyDTOs=FacultyController.getAllFaculties();
            for(FacultyDTO facultyDTO:facultyDTOs){
                cmbFaculty.addItem(facultyDTO);
            }
            facultyLoadCount++;
        } catch (Exception ex) {
            Logger.getLogger(Instructor1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadSubjectCodes(){
        subjectLoadCount=0;
        SubjectDTO subjectDTO=new SubjectDTO();
        cmbsubjects.removeAllItems();
        try {
            subjectDTO.setFacultyId(FacultyController.getFacultyId(cmbFaculty.getSelectedItem().toString()).getFacultyId());
            ArrayList<SubjectDTO> subjectDTOs=SubjectController.getRelaventSubjectCodes(subjectDTO);
            for(SubjectDTO x:subjectDTOs){
                cmbsubjects.addItem(x.getSubjectId());
            }
            subjectLoadCount++;
            setSubjectName();
        } catch (Exception ex) {
            Logger.getLogger(Instructor1.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    private void setSubjectName(){
        String subname="";
        if(cmbsubjects.getSelectedItem()!=null){
            try {
                subname=SubjectController.getRelaventSubjectNameViaCode(cmbsubjects.getSelectedItem().toString()).getSubjectName();
            } catch (Exception ex) {
                Logger.getLogger(Instructor1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            subname="";
        }
        lblsubject.setText(subname);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox cmbFaculty;
    private javax.swing.JComboBox cmbgender;
    private javax.swing.JComboBox cmbsubjects;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblsubject;
    private javax.swing.JTable tblinstructor;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtinsid;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txttelephone;
    // End of variables declaration//GEN-END:variables
}
