/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FacultyController;
import Controller.HomeController;
import DTO.FacultyDTO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author dimut
 */
public class PanelHome extends javax.swing.JPanel {

    private static PanelHome panelHome;
    private int facultyLoadCount;

    /**
     * Creates new form PanelHome
     */
    public PanelHome() {
        initComponents();
        this.setSize(2270, 1140);
        AutoCompleteDecorator.decorate(cmbFaculty);
    }

    public static PanelHome getInstance() {
        if (panelHome == null) {
            panelHome = new PanelHome();
        }
        return panelHome;
    }

    public void setInitialStage() {
        loadFaculties();
        setCounts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblNoOfSubjects = new javax.swing.JLabel();
        lblNoOfStudents = new javax.swing.JLabel();
        lblNoOfLecturers = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbFaculty = new javax.swing.JComboBox<String>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(2206, 1035));
        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel4.setText("Total Number Of Subjects");
        add(jLabel4);
        jLabel4.setBounds(410, 570, 340, 70);

        lblNoOfSubjects.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        lblNoOfSubjects.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblNoOfSubjects);
        lblNoOfSubjects.setBounds(900, 570, 720, 70);

        lblNoOfStudents.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        lblNoOfStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblNoOfStudents);
        lblNoOfStudents.setBounds(900, 370, 720, 70);

        lblNoOfLecturers.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        lblNoOfLecturers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblNoOfLecturers);
        lblNoOfLecturers.setBounds(900, 470, 720, 70);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel5.setText("Total Number Of Students");
        add(jLabel5);
        jLabel5.setBounds(410, 370, 340, 70);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel6.setText("Total Number Of Lecturers");
        add(jLabel6);
        jLabel6.setBounds(410, 470, 340, 70);

        cmbFaculty.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        cmbFaculty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFacultyItemStateChanged(evt);
            }
        });
        add(cmbFaculty);
        cmbFaculty.setBounds(800, 140, 720, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFacultyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFacultyItemStateChanged
        if (facultyLoadCount > 0) {
            setCounts();
        }
    }//GEN-LAST:event_cmbFacultyItemStateChanged

    /*Load faculties to combo box*/
    private void loadFaculties() {
        try {
            facultyLoadCount = 0;
            ArrayList<FacultyDTO> allFaculties = FacultyController.getAllFaculties();
            cmbFaculty.removeAllItems();
            for (FacultyDTO faculty : allFaculties) {
                cmbFaculty.addItem(faculty.getFacultyName());
            }
            facultyLoadCount++;
        } catch (Exception ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setCounts() {
        try {
            lblNoOfStudents.setText(HomeController.getStudentsCount(FacultyController.getFacultyId(cmbFaculty.getSelectedItem().toString()).getFacultyId()) + "");
            lblNoOfLecturers.setText(HomeController.getLecturersCount(FacultyController.getFacultyId(cmbFaculty.getSelectedItem().toString()).getFacultyId()) + "");
            lblNoOfSubjects.setText(HomeController.getSubjectsCount(FacultyController.getFacultyId(cmbFaculty.getSelectedItem().toString()).getFacultyId()) + "");
        } catch (Exception ex) {
            Logger.getLogger(PanelHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbFaculty;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblNoOfLecturers;
    private javax.swing.JLabel lblNoOfStudents;
    private javax.swing.JLabel lblNoOfSubjects;
    // End of variables declaration//GEN-END:variables
}
