/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.ArrayList;

/**
 *
 * @author dimut
 */
public class PanelPg extends javax.swing.JPanel {

    private static PanelPg panelPg;

    /**
     * Creates new form PanelPg
     */
    private PanelPg() {
        initComponents();
        setSize(2220, 300);
    }

    public static PanelPg getInstance() {
        if (panelPg == null) {
            panelPg = new PanelPg();
        }
        return panelPg;
    }
    
    public void setInitialStage() {
        clearFields();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtQualifType = new javax.swing.JTextField();
        txtinstitute = new javax.swing.JTextField();
        txtyearOfCompletion1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel18.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel18.setText("YEAR");
        add(jLabel18);
        jLabel18.setBounds(20, 240, 110, 40);

        jLabel17.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel17.setText("INSTITUTE");
        add(jLabel17);
        jLabel17.setBounds(20, 30, 160, 40);

        jLabel19.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        jLabel19.setText("QUALIFICATION");
        add(jLabel19);
        jLabel19.setBounds(20, 130, 190, 40);

        txtQualifType.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        add(txtQualifType);
        txtQualifType.setBounds(260, 130, 380, 40);

        txtinstitute.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        txtinstitute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinstituteActionPerformed(evt);
            }
        });
        add(txtinstitute);
        txtinstitute.setBounds(260, 30, 380, 40);

        txtyearOfCompletion1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        txtyearOfCompletion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyearOfCompletion1ActionPerformed(evt);
            }
        });
        add(txtyearOfCompletion1);
        txtyearOfCompletion1.setBounds(260, 230, 202, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void txtyearOfCompletion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearOfCompletion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearOfCompletion1ActionPerformed

    private void txtinstituteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinstituteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinstituteActionPerformed

    /*Check whether the textfields are empty*/
    public boolean isNotBlank() {
        return (!txtQualifType.getText().equals(null) && !txtinstitute.getText().equals(null) && !txtyearOfCompletion1.getText().equals(null));
    }
    
    /*Clear textfields*/
    public void clearFields(){
        txtQualifType.setText(null);
        txtinstitute.setText(null);
        txtyearOfCompletion1.setText(null);
    }
    
    /*Set text from student registration panel*/
    public void setAllText(ArrayList<String> text) {
        txtQualifType.setText(text.get(0));
        txtinstitute.setText(text.get(1));
        txtyearOfCompletion1.setText(text.get(2));
    }

    /*Get text to student registration panel*/
    public ArrayList<String> getAllText() {
        ArrayList<String> text = new ArrayList<>();
        text.add(txtQualifType.getText());
        text.add(txtinstitute.getText());
        text.add(txtyearOfCompletion1.getText());
        return text;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JTextField txtQualifType;
    private javax.swing.JTextField txtinstitute;
    private javax.swing.JTextField txtyearOfCompletion1;
    // End of variables declaration//GEN-END:variables
}
