/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author dimut
 */
public class WelcomePage extends javax.swing.JFrame {

    private static WelcomePage welcomePage;

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
        showDate();
        showTime();
        changeColor();
        customizeComponents();
        addHome();
    }

    public static WelcomePage getInstance() {
        if (welcomePage == null) {
            welcomePage = new WelcomePage();
        }
        return welcomePage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTimeText = new javax.swing.JLabel();
        lblDateText = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        lblTextHead = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        btnStudent = new javax.swing.JLabel();
        btnSubjects = new javax.swing.JLabel();
        btnLecturer = new javax.swing.JLabel();
        btnSemester = new javax.swing.JLabel();
        btnResults = new javax.swing.JLabel();
        btnRegistration = new javax.swing.JLabel();
        lblCourseWork = new javax.swing.JLabel();
        btnInstructor = new javax.swing.JLabel();
        pnlShow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(2560, 1440));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maxresdefault4.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 0, 657, 300);

        lblTimeText.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        lblTimeText.setForeground(new java.awt.Color(0, 95, 0));
        lblTimeText.setText("TIME");
        jPanel1.add(lblTimeText);
        lblTimeText.setBounds(1940, 100, 121, 59);

        lblDateText.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        lblDateText.setForeground(new java.awt.Color(0, 95, 0));
        lblDateText.setText("DATE");
        jPanel1.add(lblDateText);
        lblDateText.setBounds(1940, 30, 121, 61);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(2480, 10, 57, 42);

        lbldate.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        lbldate.setForeground(new java.awt.Color(0, 95, 0));
        jPanel1.add(lbldate);
        lbldate.setBounds(2130, 30, 280, 59);

        lbltime.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        lbltime.setForeground(new java.awt.Color(0, 95, 0));
        jPanel1.add(lbltime);
        lbltime.setBounds(2130, 100, 280, 59);

        lblTextHead.setFont(new java.awt.Font("Bookman Old Style", 1, 45)); // NOI18N
        lblTextHead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTextHead);
        lblTextHead.setBounds(650, 220, 1470, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 2560, 300);

        pnlButtons.setBackground(new java.awt.Color(0, 95, 153));
        pnlButtons.setLayout(null);

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        btnHome.setText("  HOME");
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setName("btnComponents"); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        pnlButtons.add(btnHome);
        btnHome.setBounds(10, 20, 270, 70);

        btnStudent.setBackground(new java.awt.Color(204, 204, 204));
        btnStudent.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graduate-student-avatar (1).png"))); // NOI18N
        btnStudent.setText("  STUDENT");
        btnStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudent.setName("btnComponents"); // NOI18N
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudentMouseClicked(evt);
            }
        });
        pnlButtons.add(btnStudent);
        btnStudent.setBounds(10, 130, 270, 70);

        btnSubjects.setBackground(new java.awt.Color(204, 204, 204));
        btnSubjects.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnSubjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books-stack-of-three.png"))); // NOI18N
        btnSubjects.setText("  SUBJECTS");
        btnSubjects.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubjects.setName("btnComponents"); // NOI18N
        btnSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubjectsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubjectsMouseEntered(evt);
            }
        });
        pnlButtons.add(btnSubjects);
        btnSubjects.setBounds(10, 660, 270, 70);

        btnLecturer.setBackground(new java.awt.Color(204, 204, 204));
        btnLecturer.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnLecturer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/conference.png"))); // NOI18N
        btnLecturer.setText("  LECTURER");
        btnLecturer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLecturer.setName("btnComponents"); // NOI18N
        btnLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLecturerMouseClicked(evt);
            }
        });
        pnlButtons.add(btnLecturer);
        btnLecturer.setBounds(10, 520, 270, 70);

        btnSemester.setBackground(new java.awt.Color(204, 204, 204));
        btnSemester.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnSemester.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exam.png"))); // NOI18N
        btnSemester.setText("  SEMESTER ");
        btnSemester.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSemester.setName("btnComponents"); // NOI18N
        btnSemester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSemesterMouseClicked(evt);
            }
        });
        pnlButtons.add(btnSemester);
        btnSemester.setBounds(10, 380, 270, 80);

        btnResults.setBackground(new java.awt.Color(204, 204, 204));
        btnResults.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnResults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exam.png"))); // NOI18N
        btnResults.setText("  RESULTS");
        btnResults.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResults.setName("btnComponents"); // NOI18N
        btnResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResultsMouseClicked(evt);
            }
        });
        pnlButtons.add(btnResults);
        btnResults.setBounds(10, 1040, 270, 70);

        btnRegistration.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-registration-filled-50.png"))); // NOI18N
        btnRegistration.setText("REGISTRATION");
        btnRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistration.setName("btnComponents"); // NOI18N
        btnRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrationMouseClicked(evt);
            }
        });
        pnlButtons.add(btnRegistration);
        btnRegistration.setBounds(10, 260, 270, 70);

        lblCourseWork.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        lblCourseWork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exam (2).png"))); // NOI18N
        lblCourseWork.setText("COURSE WORK");
        lblCourseWork.setName("btnComponents"); // NOI18N
        lblCourseWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCourseWorkMouseClicked(evt);
            }
        });
        pnlButtons.add(lblCourseWork);
        lblCourseWork.setBounds(10, 790, 270, 70);

        btnInstructor.setBackground(new java.awt.Color(204, 204, 204));
        btnInstructor.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnInstructor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/professor-with-clipboard.png"))); // NOI18N
        btnInstructor.setText("INSTRUCTOR");
        btnInstructor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInstructor.setName("btnComponents"); // NOI18N
        btnInstructor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInstructorMouseClicked(evt);
            }
        });
        pnlButtons.add(btnInstructor);
        btnInstructor.setBounds(10, 910, 270, 70);

        getContentPane().add(pnlButtons);
        pnlButtons.setBounds(0, 300, 290, 1140);

        javax.swing.GroupLayout pnlShowLayout = new javax.swing.GroupLayout(pnlShow);
        pnlShow.setLayout(pnlShowLayout);
        pnlShowLayout.setHorizontalGroup(
            pnlShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2270, Short.MAX_VALUE)
        );
        pnlShowLayout.setVerticalGroup(
            pnlShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );

        getContentPane().add(pnlShow);
        pnlShow.setBounds(290, 300, 2270, 1140);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addHome() {
        lblTextHead.setText("HOME");
        PanelHome panelHome = PanelHome.getInstance();
        panelHome.setInitialStage();
        pnlShow.removeAll();
        pnlShow.add(panelHome);
        pnlShow.setSize(panelHome.getSize());
        pnlShow.revalidate();
        pnlShow.repaint();
    }

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        addHome();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseClicked
        lblTextHead.setText("STUDENT DETAILS");
        StudentDetails stureg = StudentDetails.getInstance();
        pnlShow.removeAll();
        pnlShow.add(stureg);
        pnlShow.setSize(stureg.getSize());
        pnlShow.revalidate();
        pnlShow.repaint();;
    }//GEN-LAST:event_btnStudentMouseClicked

    private void btnSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectsMouseClicked
        setSubjectPanel();
    }//GEN-LAST:event_btnSubjectsMouseClicked

    public void setSubjectPanel() {
        lblTextHead.setText("SUBJECTS");
        Subjects subject = Subjects.getInstance();
        subject.setInitialStage();
        pnlShow.removeAll();;
        pnlShow.add(subject);
        pnlShow.setSize(subject.getSize());
        pnlShow.revalidate();
        pnlShow.repaint();
        subject.setSaveDisable();
    }

    private void btnLecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLecturerMouseClicked
        lblTextHead.setText("LECTURER DETAILS");
        Lecturer lecturer = Lecturer.getInstance();
        lecturer.setInitialStage();
        pnlShow.removeAll();
        pnlShow.add(lecturer);
        pnlShow.setSize(lecturer.getSize());
        pnlShow.revalidate();
        pnlShow.repaint();
    }//GEN-LAST:event_btnLecturerMouseClicked

    private void btnSemesterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSemesterMouseClicked
        lblTextHead.setText("SEMESTER REGISTRATION");
        SemesterRegistration semmodules = SemesterRegistration.getInstance();
        semmodules.setInitialStage();
        pnlShow.removeAll();;
        pnlShow.add(semmodules);
        pnlShow.setSize(semmodules.getSize());
        pnlShow.revalidate();;
        pnlShow.repaint();
    }//GEN-LAST:event_btnSemesterMouseClicked

    public void setPaymentsPanel() {
        lblTextHead.setText("PAYMENT DETAILS");
        Payment payment = Payment.getInstance();
        payment.setInitialStage();
        pnlShow.removeAll();
        pnlShow.add(payment);
        pnlShow.setSize(payment.getSize());
        pnlShow.revalidate();
        pnlShow.repaint();
    }

    private void btnSubjectsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubjectsMouseEntered

    private void btnResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultsMouseClicked
        setResultsPanel();
    }//GEN-LAST:event_btnResultsMouseClicked

    public void setResultsPanel() {
        lblTextHead.setText("EXAMINATION RESULTS");
        Results results = Results.getInstance();
        results.setInitialStage();
        pnlShow.removeAll();
        pnlShow.add(results);
        pnlShow.setSize(results.getSize());
        pnlShow.revalidate();
        pnlShow.repaint();
    }

    private void btnRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrationMouseClicked
        lblTextHead.setText("STUDENT REGISTRATION");
        StudentRegistration studentRegistration = StudentRegistration.getInstance();
        studentRegistration.setInitialStage();
        pnlShow.removeAll();
        pnlShow.add(studentRegistration);
        pnlShow.setSize(studentRegistration.getSize());
        pnlShow.revalidate();
        pnlShow.repaint();
    }//GEN-LAST:event_btnRegistrationMouseClicked

    private void lblCourseWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCourseWorkMouseClicked
        lblTextHead.setText("COURSE WORK DETAILS");
        CourseWork courseWork = CourseWork.getInstance();
        courseWork.setInitialStage();
        pnlShow.removeAll();
        pnlShow.add(courseWork);
        pnlShow.setSize(courseWork.getSize());
        pnlShow.revalidate();
        pnlShow.repaint();
    }//GEN-LAST:event_lblCourseWorkMouseClicked

    private void btnInstructorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstructorMouseClicked
       lblTextHead.setText("INSTRUCTOR DETAILS");
       Instructor instructor=Instructor.getInstance();
       instructor.setInitialStage();
       pnlShow.removeAll();
       pnlShow.add(instructor);
       pnlShow.setSize(instructor.getSize());
       pnlShow.revalidate();
       pnlShow.repaint();
    }//GEN-LAST:event_btnInstructorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WelcomePage.getInstance().setVisible(true);
            }
        });
    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        lbldate.setText(sdf.format(d));
    }

    void showTime() {
        new Timer(100, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
                lbltime.setText(sdf.format(d));

            }
        }).start();
    }

    private void customizeComponents() {
        Component[] components = pnlButtons.getComponents();
        for (Component component : components) {
            if (component instanceof JLabel) {
                JLabel lbl = (JLabel) component;
                if (lbl.getName() != null && lbl.getName().equals("btnComponents")) {
                    lbl.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseEntered(MouseEvent e) {
                            super.mouseEntered(e);
                            lbl.setFont(new Font("Bookman Old Style", 1, 27));
                        }

                        @Override
                        public void mouseExited(MouseEvent e) {
                            super.mouseExited(e);
                            lbl.setFont(new Font("Bookman Old Style", 1, 24));
                        }

                    });
                }
            }
        }
    }

    private void changeColor() {
        int time = 15;
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        for (int i = 20; i <= 200; i++) {
                            pnlButtons.setBackground(new Color(0, 95, i));
                            lblTextHead.setForeground(new Color(0, 95, i));
                            Thread.sleep(time);
                        }
                        for (int i = 200; i >= 20; i--) {
                            pnlButtons.setBackground(new Color(0, 95, i));
                            lblTextHead.setForeground(new Color(0, 95, i));
                            Thread.sleep(time);
                        }
                    } catch (InterruptedException ex) {
                        Logger.getLogger(WelcomePage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnInstructor;
    private javax.swing.JLabel btnLecturer;
    private javax.swing.JLabel btnRegistration;
    private javax.swing.JLabel btnResults;
    private javax.swing.JLabel btnSemester;
    private javax.swing.JLabel btnStudent;
    private javax.swing.JLabel btnSubjects;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCourseWork;
    private javax.swing.JLabel lblDateText;
    private javax.swing.JLabel lblTextHead;
    private javax.swing.JLabel lblTimeText;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbltime;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlShow;
    // End of variables declaration//GEN-END:variables
}
